CREATE TABLE IF NOT EXISTS person (
    userid INT NOT NULL PRIMARY KEY, 
    name VARCHAR(100) NOT NULL, 
    email VARCHAR(40) NOT NULL,
    imageurl VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS project (
    projectid SERIAL NOT NULL PRIMARY KEY, 
    userid INT NOT NULL, 
    projectname VARCHAR(30) NOT NULL, 
FOREIGN KEY (userid) REFERENCES person (userid) ON DELETE CASCADE 
);